# Generated by Django 5.1.1 on 2024-09-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_alter_user_gender_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrole',
            name='main_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AlterField(
            model_name='subrole',
            name='sub_role',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
