# Generated by Django 5.1.1 on 2024-09-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subrole_main_role_alter_subrole_sub_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
