# Generated by Django 5.1.1 on 2024-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
