# Generated by Django 5.1.1 on 2024-09-11 17:28

from django.db import migrations


def create_roles(apps, schema_editor):
    role = apps.get_model('users', 'Role')  # Замените <your_app_name> на имя вашего приложения

    # Список ролей, которые нужно создать
    roles = ['doctor', 'patient', 'admin']

    for role_name in roles:
        role.objects.create(role=role_name)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_user_access_key'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
