# Generated by Django 5.1.1 on 2024-09-11 17:29

from django.db import migrations


def create_sub_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    SubRole = apps.get_model('users', 'SubRole')

    # Получаем роль врача (doctor)
    doctor_role = Role.objects.get(role='doctor')

    # Список сабролей для врачей
    sub_roles = [
        'Therapist', 'Cardiologist', 'Dentist', 'Pediatrician', 'Surgeon',
        'Orthopedist', 'Neurologist', 'Dermatologist', 'Gynecologist', 'Ophthalmologist',
        'Psychiatrist', 'Oncologist', 'Urologist', 'Endocrinologist', 'Gastroenterologist',
        'Pulmonologist', 'Nephrologist', 'Hematologist', 'Rheumatologist', 'Immunologist'
    ]

    # Создаем каждый саброль, связанный с ролью "doctor"
    for sub_role_name in sub_roles:
        SubRole.objects.create(sub_role=sub_role_name, main_role=doctor_role)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_fill_roles'),
    ]

    operations = [
        migrations.RunPython(create_sub_roles),
    ]
