# Generated by Django 5.1.1 on 2024-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_fill_doctors_and_patients2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
