# Generated by Django 5.1.1 on 2024-09-19 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medicalBook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalbook',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalbook',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__role': 'doctor'}, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='book_doctor',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalbook',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__role': 'patient'}, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='book_patient',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalbook',
            name='tests',
            field=models.FileField(blank=True, null=True, upload_to='medical_tests'),
        ),
        migrations.AddField(
            model_name='medicalbook',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
