# Generated by Django 5.1.3 on 2024-11-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medicalBook', '0002_medicalbook_created_at_medicalbook_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalbook',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'roles__role': 'doctor'}, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='book_doctor',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalbook',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'roles__role': 'patient'}, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='book_patient',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
