# Generated by Django 5.1.3 on 2024-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medicalBook', '0003_alter_medicalbook_doctor_alter_medicalbook_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalbook',
            name='tests',
            field=models.FileField(blank=True, null=True, upload_to='medical_tests/'),
        ),
    ]
