services:
  - type: web
    name: hospital-system
    env: docker
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn HospitalSystem.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --threads 4 --access-logfile - --log-level info"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "HospitalSystem.settings"
    healthCheckPath: /
    autoDeploy: true
