# Generated by Django 5.1.2 on 2024-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='active_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
