# Generated by Django 5.1.2 on 2024-10-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_chatroom_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
