# Generated by Django 5.1.2 on 2024-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0004_chathistory_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
