# Generated by Django 5.1.2 on 2024-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0005_chathistory_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
