# Generated by Django 5.1.2 on 2024-10-20 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0006_chathistory_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='file_name',
        ),
    ]
