# Generated by Django 5.1.2 on 2024-10-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0007_remove_chathistory_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='active_voice_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
