# Generated by Django 5.1.1 on 2024-09-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM'), ('17:00:00', '05:00 PM')]),
        ),
    ]
