# Generated by Django 5.1.1 on 2024-09-14 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(17, 0), '05:00 PM')]),
        ),
    ]
