# Generated by Django 5.1.2 on 2024-11-14 18:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patient', '0004_appointment_end_time_alter_appointment_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'roles__role': 'doctor'},
                                    on_delete=django.db.models.deletion.CASCADE, related_name='doctor',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'roles__role': 'patient'},
                                    on_delete=django.db.models.deletion.CASCADE, related_name='patient',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[(datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'),
                                            (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'),
                                            (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '01:00 PM'),
                                            (datetime.time(14, 0), '02:00 PM'), (datetime.time(15, 0), '03:00 PM'),
                                            (datetime.time(16, 0), '04:00 PM'), (datetime.time(17, 0), '05:00 PM'),
                                            (datetime.time(18, 0), '06:00 PM')]),
        ),
    ]
